insert into centro_costos (id_centro_costo, nombre) values (1, 'Marketing');
insert into centro_costos (id_centro_costo, nombre) values (2, 'Finanzas');
insert into centro_costos (id_centro_costo, nombre) values (3, 'Investigación y Desarrollo');
insert into centro_costos (id_centro_costo, nombre) values (4, 'Finanzas');
insert into centro_costos (id_centro_costo, nombre) values (5, 'Finanzas');
insert into centro_costos (id_centro_costo, nombre) values (6, 'Investigación y Desarrollo');
insert into centro_costos (id_centro_costo, nombre) values (7, 'Ventas');
insert into centro_costos (id_centro_costo, nombre) values (8, 'Investigación y Desarrollo');
insert into centro_costos (id_centro_costo, nombre) values (9, 'Finanzas');
insert into centro_costos (id_centro_costo, nombre) values (10, 'Tecnología de la Información');
insert into centro_costos (id_centro_costo, nombre) values (11, 'Recursos Humanos');
insert into centro_costos (id_centro_costo, nombre) values (12, 'Logística');
insert into centro_costos (id_centro_costo, nombre) values (13, 'Investigación y Desarrollo');
insert into centro_costos (id_centro_costo, nombre) values (14, 'Finanzas');
insert into centro_costos (id_centro_costo, nombre) values (15, 'Investigación y Desarrollo');
insert into centro_costos (id_centro_costo, nombre) values (16, 'Recursos Humanos');
insert into centro_costos (id_centro_costo, nombre) values (17, 'Tecnología de la Información');
insert into centro_costos (id_centro_costo, nombre) values (18, 'Ventas');
insert into centro_costos (id_centro_costo, nombre) values (19, 'Investigación y Desarrollo');
insert into centro_costos (id_centro_costo, nombre) values (20, 'Recursos Humanos');
insert into centro_costos (id_centro_costo, nombre) values (21, 'Recursos Humanos');
insert into centro_costos (id_centro_costo, nombre) values (22, 'Producción');
insert into centro_costos (id_centro_costo, nombre) values (23, 'Investigación y Desarrollo');
insert into centro_costos (id_centro_costo, nombre) values (24, 'Logística');
insert into centro_costos (id_centro_costo, nombre) values (25, 'Investigación y Desarrollo');
insert into centro_costos (id_centro_costo, nombre) values (26, 'Mantenimiento');
insert into centro_costos (id_centro_costo, nombre) values (27, 'Ventas');
insert into centro_costos (id_centro_costo, nombre) values (28, 'Recursos Humanos');
insert into centro_costos (id_centro_costo, nombre) values (29, 'Ventas');
insert into centro_costos (id_centro_costo, nombre) values (30, 'Logística');
