insert into item (id_item, nombre, unidad_medida, precio_unitario) values (1, 'Achiote', 'Unidad', 6.85);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (2, 'Achiote', 'Unidad', 2.17);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (3, 'Aceite Original', 'caja', 1.46);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (4, 'Aceite Soya', 'caja', 2.07);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (5, 'Aceite Original', 'caja', 6.36);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (6, 'Oliva', 'mililitro', 6.56);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (7, 'Oliva', 'caja', 5.81);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (8, 'Aceite Soya', 'Litro', 5.56);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (9, 'Aceite Original', 'caja', 5.78);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (10, 'Girasol', 'Litro', 2.84);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (11, 'Girasol', 'Litro', 5.28);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (12, 'Achiote', 'Litro', 5.46);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (13, 'Aceite Spray Parrillada', 'Unidad', 1.03);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (14, 'Aceite Spray Parrillada', 'Unidad', 3.46);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (15, 'Aceite Spray Parrillada', 'Unidad', 6.71);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (16, 'Aceite Soya', 'caja', 4.01);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (17, 'Achiote', 'mililitro', 5.43);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (18, 'Aceite Original', 'mililitro', 4.63);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (19, 'Aceite Soya', 'caja', 4.92);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (20, 'Aceite Original', 'mililitro', 5.63);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (21, 'Achiote', 'caja', 2.54);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (22, 'Oliva', 'Unidad', 4.63);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (23, 'Achiote', 'Litro', 5.11);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (24, 'Oliva', 'Litro', 3.14);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (25, 'Aceite Soya', 'Unidad', 4.89);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (26, 'Aceite Soya', 'Unidad', 3.32);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (27, 'Oliva', 'Litro', 5.74);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (28, 'Aceite Original', 'Unidad', 5.1);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (29, 'Achiote', 'Unidad', 5.54);
insert into item (id_item, nombre, unidad_medida, precio_unitario) values (30, 'Margarina', 'Litro', 4.03);
