INSERT INTO catalogo (id_catalogo, nombre) VALUES (1, 'Electrónica');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (2, 'Ropa y Moda');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (3, 'Hogar y Muebles');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (4, 'Deportes y Fitness');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (5, 'Automotriz');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (6, 'Juguetes y Juegos');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (7, 'Salud y Belleza');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (8, 'Computación');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (9, 'Celulares y Accesorios');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (10, 'Instrumentos Musicales');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (11, 'Arte y Manualidades');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (12, 'Libros y Revistas');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (13, 'Mascotas');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (14, 'Herramientas y Construcción');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (15, 'Electrodomésticos');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (16, 'Jardinería');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (17, 'Papelería y Oficina');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (18, 'Viajes y Turismo');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (19, 'Cámaras y Fotografía');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (20, 'Videojuegos');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (21, 'Relojes y Joyas');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (22, 'Seguridad y Vigilancia');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (23, 'Iluminación');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (24, 'Bebés y Niños');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (25, 'Cine y Series');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (26, 'Muebles de Oficina');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (27, 'Ciclismo');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (28, 'Accesorios para Autos');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (29, 'Ropa Deportiva');
INSERT INTO catalogo (id_catalogo, nombre) VALUES (30, 'Drones y Accesorios');
