INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (1, 'Carlos Medina', 'Calle Bolívar 123', '0991234567', 'cmedina@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (2, 'Lucía Torres', 'Av. Colón y Amazonas', '0992345678', 'ltorres@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (3, 'Fernando Ortiz', 'Calle Sucre 456', '0993456789', 'fortiz@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (4, 'Andrea Castro', 'Av. Eloy Alfaro y 6 de Diciembre', '0994567890', 'acastro@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (5, 'Javier Herrera', 'Calle Manabí 789', '0995678901', 'jherrera@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (6, 'Sofía Ramírez', 'Av. Naciones Unidas 321', '0996789012', 'sramirez@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (7, 'Miguel Vargas', 'Calle Pichincha 654', '0997890123', 'mvargas@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (8, 'Valentina López', 'Av. América y Mariana de Jesús', '0998901234', 'vlopez@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (9, 'Pablo Ríos', 'Calle Esmeraldas 987', '0999012345', 'prios@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (10, 'Natalia Guzmán', 'Av. Simón Bolívar y Maldonado', '0990123456', 'nguzman@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (11, 'Sebastián Flores', 'Calle 10 de Agosto 147', '0991237890', 'sflores@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (12, 'Daniela Cevallos', 'Av. Shyris y Portugal', '0992348901', 'dcevallos@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (13, 'Juan Paredes', 'Calle Rocafuerte 258', '0993459012', 'jparedes@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (14, 'Mariana Salazar', 'Av. Occidental y La Gasca', '0994560123', 'msalazar@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (15, 'Gabriel Chávez', 'Calle Olmedo 369', '0995671234', 'gchavez@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (16, 'Diana Molina', 'Av. República y Pradera', '0996782345', 'dmolina@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (17, 'Andrés Peña', 'Calle Guayas 741', '0997893456', 'apena@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (18, 'Paola Jiménez', 'Av. Cordero y Reina Victoria', '0998904567', 'pjimenez@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (19, 'Ricardo León', 'Calle Manuela Cañizares 852', '0999015678', 'rleon@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (20, 'Carla Figueroa', 'Av. Seis de Diciembre y Orellana', '0990126789', 'cfigueroa@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (21, 'Eduardo Bustamante', 'Calle Ambato 963', '0991237891', 'ebustamante@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (22, 'Tatiana Cárdenas', 'Av. Maldonado y Mejía', '0992348912', 'tcardenas@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (23, 'José Villavicencio', 'Calle Loja 753', '0993459123', 'jvillavicencio@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (24, 'Alejandra Espinoza', 'Av. Brasil y Naciones Unidas', '0994560234', 'aespinoza@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (25, 'Rodrigo Palacios', 'Calle Juan Montalvo 852', '0995671345', 'rpalacios@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (26, 'Estefanía Silva', 'Av. González Suárez y Coruña', '0996782456', 'esilva@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (27, 'Cristian Zambrano', 'Calle García Moreno 951', '0997893567', 'czambrano@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (28, 'Mónica Ponce', 'Av. República y Eloy Alfaro', '0998904678', 'mponce@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (29, 'Felipe Andrade', 'Calle Napo 369', '0999015789', 'fandrade@espe.edu.ec');
INSERT INTO proveedores (id_proveedor, nombre, direccion, telefono, email) VALUES (30, 'Gabriela Rojas', 'Av. Amazonas y Naciones Unidas', '0990126890', 'grojas@espe.edu.ec');
